/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.gdal;
//jeppesen swig patch

public class AsyncReader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AsyncReader(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  protected static long getCPtr(AsyncReader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gdalJNI.delete_AsyncReader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(AsyncReader obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof AsyncReader)
      equal = (((AsyncReader)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public int GetNextUpdatedRegion(double timeout, int[] xoff, int[] yoff, int[] buf_xsize, int[] buf_ysize) {
    return gdalJNI.AsyncReader_GetNextUpdatedRegion(swigCPtr, this, timeout, xoff, yoff, buf_xsize, buf_ysize);
  }

  public int LockBuffer(double timeout) {
    return gdalJNI.AsyncReader_LockBuffer(swigCPtr, this, timeout);
  }

  public void UnlockBuffer() {
    gdalJNI.AsyncReader_UnlockBuffer(swigCPtr, this);
  }

}
