#!/bin/sh
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib

usage()
{
    cat <<EOF
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--clibs]
     [--cclibs]
     [--static-clibs]
     [--static-cclibs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
EOF
    exit $1
}
if test $# -eq 0; then
  usage 1 1>&2
fi
while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac
case $1 in
    --prefix)
    echo ${prefix}
     ;;
    --version)
    echo 3.4.2
     ;;
    --cflags)
    echo -I${prefix}/include 
      ;;
    --libs)
      # TODO: make an alias for --clibs
      # see http://trac.osgeo.org/geos/ticket/497
      echo -L${libdir} -lgeos
      ;;
    --clibs)
      echo -L${libdir} -lgeos_c
      ;;
    --cclibs)
      echo -L${libdir} -lgeos
      ;;
    --static-clibs)
      echo -L${libdir} -lgeos_c -lgeos -m
      ;;
    --static-cclibs)
      echo -L${libdir} -lgeos -m
      ;;
    --ldflags)
      echo -L${libdir}
      ;;
    --includes)
      echo ${prefix}/include
      ;;
    --jtsport)
    echo 1.12.0 
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

