/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.osr;

public class osr implements osrConstants {
  public static void UseExceptions() {
    osrJNI.UseExceptions();
  }

  public static void DontUseExceptions() {
    osrJNI.DontUseExceptions();
  }



    /* Uninstanciable class */
    private osr()
    {
    }

  public static String GetWellKnownGeogCSAsWKT(String name) {
    return osrJNI.GetWellKnownGeogCSAsWKT__SWIG_0(name);
  }

  public static String GetUserInputAsWKT(String name) {
    return osrJNI.GetUserInputAsWKT__SWIG_0(name);
  }

  public static int GetWellKnownGeogCSAsWKT(String name, String[] argout) {
    return osrJNI.GetWellKnownGeogCSAsWKT__SWIG_1(name, argout);
  }

  public static int GetUserInputAsWKT(String name, String[] argout) {
    return osrJNI.GetUserInputAsWKT__SWIG_1(name, argout);
  }

  public static java.util.Vector GetProjectionMethods() {
    return osrJNI.GetProjectionMethods();
  }

  public static String[] GetProjectionMethodParameterList(String method, String[] username) {
    return osrJNI.GetProjectionMethodParameterList(method, username);
  }

  public static void GetProjectionMethodParamInfo(String method, String param, String[] usrname, String[] type, double[] defaultval) {
    osrJNI.GetProjectionMethodParamInfo(method, param, usrname, type, defaultval);
  }

}
