/* Source/NCSBuildGnu/NCSGnuConfig.h.  Generated by configure.  */
/* Source/NCSBuildGnu/NCSGnuConfig.h.in.  Generated from configure.in by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "libecwj2"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libecwj2 3.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libecwj2"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.3"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
